'use strict';

const fs = require('fs');
const path = require('path');
const { getModuleLogger } = require('../utils/logger');
const { withRetry } = require('../utils/retry');

const log = getModuleLogger('visual-engine');

/**
 * Download a file from URL to local path.
 */
async function downloadFile(url, outputPath) {
  const res = await fetch(url, { signal: AbortSignal.timeout(60000) });
  if (!res.ok) throw new Error(`Download failed: HTTP ${res.status} from ${url}`);
  const buffer = Buffer.from(await res.arrayBuffer());
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(outputPath, buffer);
}

// ============================================================
// Pollinations.ai — AI Image Generation (PRIMARY + ONLY)
// No API key required. URL-based generation. 1080x1920 portrait.
// ============================================================

/**
 * Smart Keyword Extraction for Stock API
 * Extracts the first 2-3 significant words from a massive LLM prompt
 */
function extractKeywords(prompt) {
  let cleaned = prompt.replace(/^(A|An|The)\s+/i, ''); // Strip articles
  cleaned = cleaned.split(',')[0].trim(); // Take first phrase before comma
  const words = cleaned.split(' ').filter(w => w.length > 2); // Ignore tiny words like 'in', 'of'
  return words.slice(0, 3).join(' '); // Return up to 3 strong keywords
}

/**
 * Fallback to Pexels or Pixabay
 */
async function fetchStockImage(prompt, outputPath) {
  const query = extractKeywords(prompt);
  log.info(`Pollinations failed. Stock Fallback: searching for "${query}"`);

  // Try Pexels
  if (process.env.PEXELS_API_KEY) {
    try {
      const res = await fetch(`https://api.pexels.com/v1/search?query=${encodeURIComponent(query)}&orientation=portrait&per_page=3`, {
        headers: { 'Authorization': process.env.PEXELS_API_KEY }
      });
      if (res.ok) {
        const data = await res.json();
        if (data.photos && data.photos.length > 0) {
          // Grab a random one from top 3 to avoid extreme repetition
          const photo = data.photos[Math.floor(Math.random() * data.photos.length)];
          await downloadFile(photo.src.portrait || photo.src.large, outputPath);
          return 'Pexels';
        }
      }
    } catch (err) { log.warn(`Pexels fallback failed: ${err.message}`); }
  }

  // Try Pixabay
  if (process.env.PIXABAY_API_KEY) {
    try {
      const res = await fetch(`https://pixabay.com/api/?key=${process.env.PIXABAY_API_KEY}&q=${encodeURIComponent(query)}&image_type=photo&orientation=vertical`);
      if (res.ok) {
        const data = await res.json();
        if (data.hits && data.hits.length > 0) {
          const hit = data.hits[Math.floor(Math.random() * Math.min(data.hits.length, 3))];
          await downloadFile(hit.largeImageURL, outputPath);
          return 'Pixabay';
        }
      }
    } catch (err) { log.warn(`Pixabay fallback failed: ${err.message}`); }
  }

  throw new Error('Stock API fallback exhausted or keys not configured');
}

/**
 * Generate 3 AI images from the LLM's imagePrompts using Pollinations.ai.
 * Fallbacks to Pixabay/Pexels if Pollinations drops a 502/timeout.
 *
 * @param {string[]} imagePrompts - Array of exactly 3 descriptive prompts from the LLM
 * @param {string[]} videoEffects - Array of exactly 3 FFmpeg effect names from the LLM
 * @param {string} outputDir - Directory to save images
 * @returns {Promise<Array>} clips array
 */
async function fetchPollinationsImages(imagePrompts, videoEffects, outputDir) {
  const clips = [];

  for (let i = 0; i < imagePrompts.length && i < 3; i++) {
    const prompt = imagePrompts[i];
    const effect = videoEffects?.[i] || 'zoom_in';
    const imgPath = path.join(outputDir, `ai_image_${i}.jpg`);
    let sourceProvider = 'pollinations-failed';
    let attributionText = '';

    try {
      // 1. Primary Route: Pollinations
      const url = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=1080&height=1920&nologo=true`;
      
      await withRetry(async () => {
        await downloadFile(url, imgPath);
        const stat = fs.statSync(imgPath);
        if (stat.size < 10000) throw new Error('Image too small — generation likely failed');
      }, { maxRetries: 2, name: `pollinations-img-${i}`, baseDelay: 2000 });
      
      sourceProvider = `pollinations-${i}`;
      attributionText = 'Generated by Pollinations.ai';
      log.info(`Pollinations: Generated image ${i + 1}/3 with effect "${effect}"`);
      
    } catch (err) {
      log.warn(`Pollinations failed, falling back to Stock API. Error: ${err.message}`);
      
      // 2. Fallback Route: Stock API
      try {
        const stockProvider = await fetchStockImage(prompt, imgPath);
        sourceProvider = `stock-${stockProvider}-${i}`;
        attributionText = `Visuals provided by ${stockProvider}`;
        log.info(`Stock Fallback: Sourced image ${i + 1}/3 via ${stockProvider}`);
      } catch (fallbackErr) {
        log.error(`Critical Visual Failure on segment ${i}: Stock provider also failed! (${fallbackErr.message})`);
        continue; // Skip appending if even fallback fails, but assembly engine can still concat what it has
      }
    }

    // Push into clips if downloaded successfully
    if (fs.existsSync(imgPath)) {
      clips.push({
        path: imgPath,
        type: 'image',
        effect,
        source: sourceProvider,
        attribution: attributionText
      });
    }
  }

  return clips;
}

// ============================================================
// MAIN VISUAL ACQUISITION
// ============================================================

/**
 * Acquire AI-generated visuals for a video using the LLM's imagePrompts.
 *
 * @param {Object} scriptJson - LLM output with imagePrompts[] and videoEffects[]
 * @param {number} targetDurationMs - Total audio duration (used for logging)
 * @param {string} outputDir - Directory to save images
 * @returns {Promise<{clips: Array, provider: string, attributions: string[]}>}
 */
async function acquireVisuals(scriptJson, targetDurationMs, outputDir = '/tmp/build/clips') {
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

  // The new schema uses imagePrompts and videoEffects from the LLM
  const imagePrompts = scriptJson.imagePrompts || [
    'A glowing cyberpunk hacker typing furiously in neon-lit server room, 8K, ultra-detailed',
    'Abstract AI neural network visualization, vibrant colors, futuristic digital art, 8K',
    'Futuristic holographic tech display in a dark room, dramatic lighting, cinematic, 8K'
  ];
  const videoEffects = scriptJson.videoEffects || ['zoom_in', 'cyberpunk_color', 'glitch'];

  log.info(`Generating ${imagePrompts.length} AI images from LLM prompts via Pollinations...`);

  const clips = await fetchPollinationsImages(imagePrompts, videoEffects, outputDir);

  if (clips.length === 0) {
    throw new Error('ALL_VISUAL_PROVIDERS_EXHAUSTED — no images could be generated by Pollinations');
  }

  const attributions = clips.map(c => c.attribution);
  const durationPerImage = Math.round(targetDurationMs / clips.length);
  // Assign even duration splits per image for assembly engine
  clips.forEach(c => { c.durationMs = durationPerImage; });

  log.info(`Visuals acquired: ${clips.length} AI images, ~${Math.round(targetDurationMs / 1000)}s total`);
  return { clips, provider: 'pollinations', attributions };
}

module.exports = { acquireVisuals };
