'use strict';

const fs = require('fs');
const path = require('path');
const { getModuleLogger } = require('../utils/logger');
const { withRetry } = require('../utils/retry');

const log = getModuleLogger('visual-engine');

/**
 * Download a file from URL to local path.
 */
async function downloadFile(url, outputPath) {
  const res = await fetch(url, { signal: AbortSignal.timeout(60000) });
  if (!res.ok) throw new Error(`Download failed: HTTP ${res.status} from ${url}`);
  const buffer = Buffer.from(await res.arrayBuffer());
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(outputPath, buffer);
}

// ============================================================
// Pollinations.ai — AI Image Generation (PRIMARY + ONLY)
// No API key required. URL-based generation. 1080x1920 portrait.
// ============================================================

/**
 * Generate 3 AI images from the LLM's imagePrompts using Pollinations.ai.
 *
 * @param {string[]} imagePrompts - Array of exactly 3 descriptive prompts from the LLM
 * @param {string[]} videoEffects - Array of exactly 3 FFmpeg effect names from the LLM
 * @param {string} outputDir - Directory to save images
 * @returns {Promise<Array>} clips array
 */
async function fetchPollinationsImages(imagePrompts, videoEffects, outputDir) {
  const clips = [];

  for (let i = 0; i < imagePrompts.length && i < 3; i++) {
    const prompt = imagePrompts[i];
    const effect = videoEffects?.[i] || 'zoom_in';

    try {
      const url = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=1080&height=1920&nologo=true`;
      const imgPath = path.join(outputDir, `ai_image_${i}.jpg`);

      await withRetry(async () => {
        await downloadFile(url, imgPath);
        const stat = fs.statSync(imgPath);
        if (stat.size < 10000) throw new Error('Image too small — generation likely failed');
      }, { maxRetries: 3, name: `pollinations-img-${i}`, baseDelay: 4000 });

      clips.push({
        path: imgPath,
        type: 'image',
        effect,
        source: `pollinations-${i}`,
        attribution: 'Generated by Pollinations.ai'
      });

      log.info(`Pollinations: Generated image ${i + 1}/3 with effect "${effect}"`);
    } catch (err) {
      log.warn(`Pollinations image ${i} failed: ${err.message}`);
    }
  }

  return clips;
}

// ============================================================
// MAIN VISUAL ACQUISITION
// ============================================================

/**
 * Acquire AI-generated visuals for a video using the LLM's imagePrompts.
 *
 * @param {Object} scriptJson - LLM output with imagePrompts[] and videoEffects[]
 * @param {number} targetDurationMs - Total audio duration (used for logging)
 * @param {string} outputDir - Directory to save images
 * @returns {Promise<{clips: Array, provider: string, attributions: string[]}>}
 */
async function acquireVisuals(scriptJson, targetDurationMs, outputDir = '/tmp/build/clips') {
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

  // The new schema uses imagePrompts and videoEffects from the LLM
  const imagePrompts = scriptJson.imagePrompts || [
    'A glowing cyberpunk hacker typing furiously in neon-lit server room, 8K, ultra-detailed',
    'Abstract AI neural network visualization, vibrant colors, futuristic digital art, 8K',
    'Futuristic holographic tech display in a dark room, dramatic lighting, cinematic, 8K'
  ];
  const videoEffects = scriptJson.videoEffects || ['zoom_in', 'cyberpunk_color', 'glitch'];

  log.info(`Generating ${imagePrompts.length} AI images from LLM prompts via Pollinations...`);

  const clips = await fetchPollinationsImages(imagePrompts, videoEffects, outputDir);

  if (clips.length === 0) {
    throw new Error('ALL_VISUAL_PROVIDERS_EXHAUSTED — no images could be generated by Pollinations');
  }

  const attributions = clips.map(c => c.attribution);
  const durationPerImage = Math.round(targetDurationMs / clips.length);
  // Assign even duration splits per image for assembly engine
  clips.forEach(c => { c.durationMs = durationPerImage; });

  log.info(`Visuals acquired: ${clips.length} AI images, ~${Math.round(targetDurationMs / 1000)}s total`);
  return { clips, provider: 'pollinations', attributions };
}

module.exports = { acquireVisuals };
